"""add agent categories

Revision ID: 42acf6f0e0fb
Revises: 2adcbe1f5dfb
Create Date: 2025-06-07 14:09:26.481652

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42acf6f0e0fb'
down_revision = 'add_user_wechat_phone'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_categories',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', models.types.StringUUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_category_pkey')
    )
    with op.batch_alter_table('agent_categories', schema=None) as batch_op:
        batch_op.create_index('agent_category_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('agent_category_apps',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('category_id', models.types.StringUUID(), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name='fk_agent_category_apps_app_id'),
    sa.ForeignKeyConstraint(['category_id'], ['agent_categories.id'], name='fk_agent_category_apps_category_id'),
    sa.PrimaryKeyConstraint('id', name='agent_category_app_pkey'),
    sa.UniqueConstraint('category_id', 'app_id', name='unique_category_app')
    )
    with op.batch_alter_table('agent_category_apps', schema=None) as batch_op:
        batch_op.create_index('agent_category_app_app_idx', ['app_id'], unique=False)
        batch_op.create_index('agent_category_app_category_idx', ['category_id'], unique=False)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('agent_category_apps', schema=None) as batch_op:
        batch_op.drop_index('agent_category_app_category_idx')
        batch_op.drop_index('agent_category_app_app_idx')

    op.drop_table('agent_category_apps')
    with op.batch_alter_table('agent_categories', schema=None) as batch_op:
        batch_op.drop_index('agent_category_tenant_id_idx')

    op.drop_table('agent_categories')
    # ### end Alembic commands ###
