"""add item types to agent categories

Revision ID: add_item_types_to_agent_categories
Revises: 42acf6f0e0fb
Create Date: 2025-06-07 15:00:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_agent_item_types'
down_revision = '42acf6f0e0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_category_apps', schema=None) as batch_op:
        # 添加新字段
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), server_default=sa.text("'app'"), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('icon_background', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('markdown_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=1000), nullable=True))
        
        # 修改app_id字段为可空
        batch_op.alter_column('app_id', nullable=True)
    # ### end Alembic commands ###


def upgrade_data():
    """数据迁移：为现有记录设置默认值"""
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE agent_category_apps 
        SET item_type = 'app' 
        WHERE item_type IS NULL OR item_type = ''
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_category_apps', schema=None) as batch_op:
        # 移除新添加的字段
        batch_op.drop_column('url')
        batch_op.drop_column('markdown_content')
        batch_op.drop_column('icon_background')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('item_type')
        
        # 恢复app_id字段为非空
        batch_op.alter_column('app_id', nullable=False)
    # ### end Alembic commands ### 