"""add user wechat work id and phone fields

Revision ID: add_user_wechat_phone
Revises: 42acf6f0e0fb
Create Date: 2025-06-08 12:00:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_wechat_phone'
down_revision = '4474872b0ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wechat_work_id', sa.String(length=255), nullable=True, comment='企业微信ID'))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号码'))
        batch_op.create_index('account_wechat_work_id_idx', ['wechat_work_id'], unique=False)
        batch_op.create_index('account_phone_idx', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('account_phone_idx')
        batch_op.drop_index('account_wechat_work_id_idx')
        batch_op.drop_column('phone')
        batch_op.drop_column('wechat_work_id')
    # ### end Alembic commands ### 