name: Build docker image manually

on:
  workflow_dispatch:
    inputs:
      service:
        description: '选择要构建的服务'
        required: true
        type: choice
        options:
          - api
          - web
          - all
      platform:
        description: '选择构建平台'
        required: true
        type: choice
        options:
          - amd64
          - arm64
          - all

concurrency:
  group: docker-build-manual-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_name: "api-amd64"
            platform: linux/amd64
            context: "api"
            file: "api/Dockerfile"
          - service_name: "api-arm64"
            platform: linux/arm64
            context: "api"
            file: "api/Dockerfile"
          - service_name: "web-amd64"
            platform: linux/amd64
            context: "web"
            file: "web/Dockerfile"
          - service_name: "web-arm64"
            platform: linux/arm64
            context: "web"
            file: "web/Dockerfile"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 